/* SPDX-License-Identifier: BSD-3-Clause */
/*
 * Copyright (c) 2020 Rockchip Electronics Co., Ltd.
 */

#include "hal_base.h"
#include "unity.h"
#include "unity_fixture.h"

#ifdef UNITY_HAL_LEAGACY

#ifdef UNITY_HAL_COREMARK
#include "coremark.h"
#endif

TEST_GROUP(HAL_LEAGACY);

TEST_SETUP(HAL_LEAGACY){
}

TEST_TEAR_DOWN(HAL_LEAGACY){
}

#ifdef UNITY_HAL_DATA_ACCESS
#define BUFFER_SIZE (4 * 1024) /* Config the size of test buffer */

static char *AlignUp(char *ptr, int32_t align)
{
    return (char *)(((uintptr_t)ptr + align - 1) & ~(uintptr_t)(align - 1));
}

static void *AllocBuffer(void * *buf1_, int32_t size)
{
    char * *buf1 = (char * *)buf1_;
    char *buf, *ptr;

    if (!buf1 || size < 0) {
        size = 0;
    }

    ptr = buf = (char *)malloc(size + CACHE_LINE_SIZE);
    memset(buf, 0xCC, size + CACHE_LINE_SIZE);

    *buf1 = AlignUp(ptr, CACHE_LINE_SIZE);

    return buf;
}

static uint32_t MyCpy(uint32_t *dst, uint32_t *src, uint32_t size)
{
    uint32_t i;

    for (i = 0; i < (size / 4); i++) {
        dst[i] = src[i];
    }

    return 0;
}

static void DataAccessHelper(uint32_t *srcbuf, uint32_t *dstbuf, uint32_t (*f)(uint32_t *, uint32_t *, uint32_t))
{
    uint64_t timCount[4], gap;
    struct CACHE_PMU_CNT pmuStatus[4];
    uint32_t us;

    /* 1st test */
    HAL_DCACHE_CleanInvalidate();
    HAL_DCACHE_GetPMU(&pmuStatus[0]);
    timCount[0] = HAL_TIMER_GetCount(SYS_TIMER);
    f(dstbuf, srcbuf, BUFFER_SIZE);
    timCount[1] = HAL_TIMER_GetCount(SYS_TIMER);
    HAL_DCACHE_GetPMU(&pmuStatus[1]);

    /* 2nd test */
    HAL_DCACHE_GetPMU(&pmuStatus[2]);
    timCount[2] = HAL_TIMER_GetCount(SYS_TIMER);
    f(dstbuf, srcbuf, BUFFER_SIZE);
    timCount[3] = HAL_TIMER_GetCount(SYS_TIMER);
    HAL_DCACHE_GetPMU(&pmuStatus[3]);

    HAL_DBG("1: cache miss\n");
    HAL_DBG("start timer count %ld%ld\n", (uint32_t)(timCount[0] >> 32), (uint32_t)(timCount[0]));
    HAL_DBG("end timer count %ld%ld\n", (uint32_t)(timCount[1] >> 32), (uint32_t)(timCount[1]));
    HAL_DBG("PMU read hit/total=%lu/%lu\n",
            pmuStatus[1].rdHit - pmuStatus[0].rdHit,
            pmuStatus[1].rdNum - pmuStatus[0].rdNum);
    HAL_DBG("PMU read miss penalty %lu\n", pmuStatus[1].rdMissPenalty - pmuStatus[0].rdMissPenalty);
    if (timCount[1] > timCount[0]) {
        gap = timCount[1] - timCount[0];
    } else {
        gap = timCount[0] - timCount[1];
    }
    us = HAL_DivU64(gap, PLL_INPUT_OSC_RATE / 1000000);
    HAL_DBG("data %d bytes, cost %ld us(gap %lld), about %ld KB/s\n", BUFFER_SIZE, us, gap, 1000000 / us * BUFFER_SIZE / 1024);

    HAL_DBG("2: cache hit\n");
    HAL_DBG("start timer count %ld%ld\n", (uint32_t)(timCount[2] >> 32), (uint32_t)(timCount[2]));
    HAL_DBG("end timer count %ld%ld\n", (uint32_t)(timCount[3] >> 32), (uint32_t)(timCount[3]));
    HAL_DBG("PMU read hit/total=%lu/%lu\n",
            pmuStatus[3].rdHit - pmuStatus[2].rdHit,
            pmuStatus[3].rdNum - pmuStatus[2].rdNum);
    HAL_DBG("PMU read miss penalty %lu\n", pmuStatus[3].rdMissPenalty - pmuStatus[2].rdMissPenalty);
    if (timCount[3] > timCount[2]) {
        gap = timCount[3] - timCount[2];
    } else {
        gap = timCount[2] - timCount[3];
    }
    us = HAL_DivU64(gap, PLL_INPUT_OSC_RATE / 1000000);
    HAL_DBG("data %d bytes, cost %ld us(gap %lld), about %ld KB/s\n", BUFFER_SIZE, us, gap, 1000000 / us * BUFFER_SIZE / 1024);
    HAL_ICACHE_DisablePMU();
}

TEST(HAL_LEAGACY, DataAccess){
    uint32_t *xipbuf, *srcbuf, *dstbuf;
    void *poolbuf1, *poolbuf2;

    HAL_DBG("\nDataAccess\n");
    HAL_DCACHE_EnablePMU();

    poolbuf1 = AllocBuffer((void * *)&srcbuf, BUFFER_SIZE);
    poolbuf2 = AllocBuffer((void * *)&dstbuf, BUFFER_SIZE);

    HAL_DBG("SRAM DataAccess\n");
    memset(srcbuf, 0xa5, BUFFER_SIZE);
    memset(dstbuf, 0x5a, BUFFER_SIZE);
    DataAccessHelper(srcbuf, dstbuf, (void *)&MyCpy);
    HAL_DBG("src point %p dst[0] %lx dst[1]%lx src[0]%lx src[1]%lx\n", srcbuf, dstbuf[0], dstbuf[1], srcbuf[0], srcbuf[1]);

#ifdef XIP_MEM_BASE
    xipbuf = (uint32_t *)(0x60000000 + 0x4000);
    struct SNOR_HOST *spi = (struct SNOR_HOST *)calloc(1, sizeof(struct SNOR_HOST));
    struct HAL_FSPI_HOST *host = (struct HAL_FSPI_HOST *)calloc(1, sizeof(*host));
    struct SPI_NOR *nor = (struct SPI_NOR *)calloc(1, sizeof(struct SPI_NOR));

    nor->spi = spi;

    host = (struct HAL_FSPI_HOST *)calloc(1, sizeof(struct HAL_FSPI_HOST));
    host->instance = FSPI0;
    HAL_FSPI_Init(host);
    nor->spi->userdata = (void *)host;
    nor->spi->mode = HAL_SPI_MODE_3 | HAL_SPI_TX_QUAD | HAL_SPI_RX_QUAD;
    nor->spi->xfer = HAL_FSPI_SpiXfer;
    nor->spi->mode |= HAL_SPI_XIP;
    nor->spi->xipConfig = HAL_FSPI_SpiXipConfig;

    /* Init spi nor abstract */
    HAL_SNOR_Init(nor);

    HAL_SNOR_XIPEnable(nor);
    HAL_DBG("SNOR XIP DataAccess\n");
    DataAccessHelper(xipbuf, dstbuf, (void *)&MyCpy);
    HAL_DBG("src point %p dst[0] %lx dst[1]%lx src[0]%lx src[1]%lx\n", xipbuf, dstbuf[0], dstbuf[1], xipbuf[0], xipbuf[1]);
    HAL_SNOR_XIPDisable(nor);
#endif

    free(poolbuf1);
    free(poolbuf2);

    HAL_SNOR_DeInit(nor);
}
#endif

#ifdef UNITY_HAL_THROUGHPUT
static void NopTest(void)
{
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
    __NOP();
}

TEST(HAL_LEAGACY, CodePerformance){
    uint64_t timCount[4];
    struct CACHE_PMU_CNT pmuStatus[4];

    HAL_DBG("\nCodePerformance\n");
    HAL_ICACHE_EnablePMU();
    HAL_ICACHE_GetPMU(&pmuStatus[0]);
    timCount[0] = HAL_TIMER_GetCount(SYS_TIMER);
    NopTest();
    timCount[1] = HAL_TIMER_GetCount(SYS_TIMER);
    HAL_ICACHE_GetPMU(&pmuStatus[1]);

    HAL_ICACHE_GetPMU(&pmuStatus[2]);
    timCount[2] = HAL_TIMER_GetCount(SYS_TIMER);
    NopTest();
    timCount[3] = HAL_TIMER_GetCount(SYS_TIMER);
    HAL_ICACHE_GetPMU(&pmuStatus[3]);

    HAL_DBG("1: cache miss\n");
    HAL_DBG("start timer count %ld%ld\n", (uint32_t)(timCount[0] >> 32), (uint32_t)(timCount[0]));
    HAL_DBG("end timer count %ld%ld\n", (uint32_t)(timCount[1] >> 32), (uint32_t)(timCount[1]));
    HAL_DBG("PMU read hit/total=%lu/%lu\n",
            pmuStatus[1].rdHit - pmuStatus[0].rdHit,
            pmuStatus[1].rdNum - pmuStatus[0].rdNum);
    HAL_DBG("PMU read miss penalty %lu\n", pmuStatus[1].rdMissPenalty - pmuStatus[0].rdMissPenalty);

    HAL_DBG("2: cache hit\n");
    HAL_DBG("start timer count %ld%ld\n", (uint32_t)(timCount[2] >> 32), (uint32_t)(timCount[2]));
    HAL_DBG("end timer count %ld%ld\n", (uint32_t)(timCount[3] >> 32), (uint32_t)(timCount[3]));
    HAL_DBG("PMU read hit/total=%lu/%lu\n",
            pmuStatus[3].rdHit - pmuStatus[2].rdHit,
            pmuStatus[3].rdNum - pmuStatus[2].rdNum);
    HAL_DBG("PMU read miss penalty %lu\n", pmuStatus[3].rdMissPenalty - pmuStatus[2].rdMissPenalty);
    HAL_ICACHE_DisablePMU();
}
#endif

#ifdef UNITY_HAL_COREMARK
TEST(HAL_LEAGACY, CoreMark){
    coremark_main();
}
#endif

/* I/D cache should be preseted and enable */
TEST_GROUP_RUNNER(HAL_LEAGACY){
#ifdef UNITY_HAL_THROUGHPUT
    RUN_TEST_CASE(HAL_LEAGACY, CodePerformance);
#endif

#ifdef UNITY_HAL_DATA_ACCESS
    RUN_TEST_CASE(HAL_LEAGACY, DataAccess);
#endif

#ifdef UNITY_HAL_COREMARK
    RUN_TEST_CASE(HAL_LEAGACY, CoreMark);
#endif
}

#endif
